### ISSUE TITLE
sticky nav should be enabled by default (on update to 0.4)

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#377] opened 2015-01-28 16:13 UTC
I think?

**Comment by benlk** [comment] 2015-02-16 17:02
Using the sticky header is the default set in `options.php` in 0.4, and it wasn't an option in 0.3, so it should be the new default when people upgrade from 0.3.

If they're upgrading from the develop branch, then the upgrade process won't change their previous option.

**Comment by aschweigert** [comment] 2015-02-16 18:10
right...as far as i can tell, from the sites i've done so far, it's NOT enabled when the update script runs so the default is not being recognized, for some reason

**Comment by benlk** [comment] 2015-02-17 14:54
Strange. From a clean install of everything, the defaults are actually enabled before you run the update when going to the post editor. The defaults are probably created at other times as well. Here's what I did to try to reproduce:

- created a new vagrant box with a fresh install of largo-umbrella and WP 4.1
- activated 0.3 and saved theme options, changing nothing from the default values
- took a vagrant snapshot
- switched to 0.4 and ran the database update
- created a long test post, then viewed the post
- the sticky nav was active
- inserted a var_log function into the theme function: `show_sticky_nav` is set to `1`.

Okay, so that's how it looks when you run the update. What if you don't run the update?

- rolled back to the 0.3 snapshot
- add a function to largo-dev to report the value of `show-sticky-nav`
- enabled 0.4: `show_sticky_nav` is `false`
- created a post and saved it: `show_sticky_nav` is `1`
- ran updates: `show_sticky_nav` is `1`

Let's create a function in the updates to force `show_sticky_nav` to be `false`.

- rolled back to the 0.3 snapshot
- add a function to largo-dev's update.php to `of_set_option('show_sticky_nav', false);`
- enabled 0.4: `show_sticky_nav` is `false`
- opened the post editor: `show_sticky_nav` is `1`
- created a post and saved it: `show_sticky_nav` is `1`
- ran the 0.4 database update with the function to force it to be false: `show_sticky_nav` is `false`

Since the process of creating the defaults is kind of uncertain, and we're currently depending on unknown behavior to set `show_sticky_nav` to the default, I'll file a PR with the code to force it to update.

**Comment by benlk** [comment] 2015-02-19 21:44
PR for this was #406, which was merged in.

**Closed by benlk** 2015-02-19 21:44 UTC
Labels: priority: normal, type: improvement
