### ISSUE TITLE
Landing Pages: Menus

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#407] opened 2015-02-17 15:46 UTC
Feature request: Please add Landing Pages to the Edit Menus Options.

**Comment by aschweigert** [comment] 2015-02-17 15:54
duplicate of #399 

essentially you would just add the "series" to the menu that corresponded to the landing page (because the landing pages just replace the default taxonomy archive pages)

There's a bug we noticed recently though where, in multisite at least, the custom taxonomies are only available to network administrators on the regular menu management page so we're looking into a fix for that (because they should be available to site administrators as well).

**Closed** 2015-02-17 15:54 UTC
Labels: type: duplicate

**Comment by ithacaindy** [comment] 2015-02-17 16:00
What is odd with using Series in menus (at least in the case of the Independent) is that those links bounce back to the frontpage. Landing pages, on the other hand, attached to the Series, behave normally.

**Comment by aschweigert** [comment] 2015-02-17 16:04
Hm, that's odd. Do you have an example?

**Comment by ithacaindy** [comment] 2015-02-17 16:16
I created  "Tools-Test" series (still available for testing), adding it to the menu at vtinq.org. When I click on the menu item, the browser returns to the frontpage.

**Comment by ithacaindy** [comment] 2015-02-17 16:28
OK. The problem was the cache plugin, WP Super Cache. I deleted the cache and the series works.

**Comment by aschweigert** [comment] 2015-02-17 16:29
Ah, ok. That makes sense. You'd probably have to flush the cache anytime you update the menus to avoid weird things like that happening because of how the landing pages stuff rewrites URLs
