### ISSUE TITLE
let editor and above embed iframes

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#834] opened 2015-08-12 20:42 UTC
because why is this limited to super admins that's silly

see also: http://jira.inn.org/browse/CUC-6

**Comment by aschweigert** [comment] 2015-08-12 20:48
possibly just incorporate https://wordpress.org/plugins/unfiltered-mu/

**Comment by benlk** [comment] 2015-12-09 16:01
This looks like a duplicate of #276.

**Closed** 2015-12-09 16:05 UTC
Labels: priority: high, type: improvement
