### ISSUE TITLE
Sample-Child: Sticky menu Obscures Headlines

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#374] opened 2015-01-27 23:58 UTC
I've found the sample child theme is also obscuring article headlines.

![screen](https://cloud.githubusercontent.com/assets/3837773/5929855/6b77b480-a656-11e4-80cc-419b038381f8.png)

**Comment by aschweigert** [comment] 2015-01-28 00:42
Hi Ed - So the new child theme is intended as an example, you may want to strip out a lot of it if you're not using it. A child theme really only needs a style.css file with the relevant header block but we wanted to create an example theme that was as explicit as possible about the best ways to do certain things because we've had a lot of developers ask for that. 

Do you have a lot of custom CSS in the child theme or anything? That could also be causing some of these issues since some of the structure of the pages has changed in this new version so you may need to revisit any custom CSS you've written and do some testing to make sure everything is working as intended with the new version.

**Comment by willhaynes** [comment] 2015-01-28 05:33
I ran into something similar to this weekend. I bet the issue here is a javascript error getting thrown and halting js, as the sticky header relies entirely on js to get a height set.

**Comment by aschweigert** [comment] 2015-01-28 14:12
Yeah, that's actually what I'm wondering about re: the sample child theme. Although I think it shouldn't cause any issues like that. Could also be plugin related too so it just depends what all you have installed.

**Comment by ithacaindy** [comment] 2015-01-28 15:37
I cured the problem by first disabling all plugins, setting the sample child theme to newspaper layout, then enabling the plugins. I'd like to learn how to add to the newspaper layout the  left/middle/right sidebars available to the full-screen layout's bottom. Or learn where the bottom layout code is hidden, now that home.php is gone.

**Comment by aschweigert** [comment] 2015-01-28 15:41
We retained the ability to have either a list of stories ("river") below the homepage top section OR a widget area OR show nothing (which is what the new hero layouts typically use because the three widgets you're describing are actually built into the layout). I think you should be able to just use the "widget area" option to do what you're describing.

**Comment by aschweigert** [comment] 2015-01-28 16:43
leaving this open for now because it sounds like there *might* be an issue with the homepage layout (in the bottom widget area when using that newspaper top layout option) here, let's do a little more testing before closing this out

**Comment by willhaynes** [comment] 2015-02-06 19:50
I'm almost positive it's a js error. Possibly still something with Largo. Ed, is this on staging somewhere I can take a look?

**Comment by willhaynes** [comment] 2015-03-11 13:43
Since we haven't been able to replicate this issue, I'm going to close this for now. Feel free to re-open if the issue resurfaces.

**Closed by willhaynes** 2015-03-11 13:43 UTC
Labels: priority: normal, type: question
