### ISSUE TITLE
featured media - bug with setting a featured image after removing a gallery

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#392] opened 2015-02-03 16:45 UTC
Steps to reproduce:

1) from the featured media editor, create a gallery and set it as featured
2) click on "add featured media" button again and then click "cancel gallery"
3) attempt to set an image as featured instead

When I do that I get kicked to blank "edit gallery" page and everything is broken (the X to close the window doesn't even work)

**Comment by tothebeat** [comment] 2015-03-23 20:08
The issue is a little different than Adam stated. Here are the steps I use to reproduce the issue, starting from being on the Dashboard of the site.

1. Click "Posts -> Add New"
  ![image](https://cloud.githubusercontent.com/assets/486230/6789130/0fb56700-d16c-11e4-9323-fb8379d1ee8b.png)

2. Click "Set Featured Media" button
  ![image](https://cloud.githubusercontent.com/assets/486230/6789144/2e26a47e-d16c-11e4-8bd9-b3f879883b0c.png)

3. Click "Featured gallery"
  ![image](https://cloud.githubusercontent.com/assets/486230/6789163/499e67e6-d16c-11e4-9f2e-9b5472702867.png)

4. Create a basic gallery with one image. Click "Create a new gallery" button.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789196/92283280-d16c-11e4-8373-0275180304c9.png)

5. In the _Edit Gallery_ window, accept the defaults and click the "Set as featured" button.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789211/c3875888-d16c-11e4-8315-546096a984ea.png)

6. Click the "Edit Featured Media" button that has replaced the original "Add Featured Media" button.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789231/e69c6048-d16c-11e4-8638-9de9510d0dbb.png)

7. The _Edit Gallery_ window appears again. Click the "Cancel Gallery" link in the top left corner.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789260/0384d08c-d16d-11e4-90a5-2c955e6d15b7.png)

8. Click the "Featured image" link.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789268/1446ec7a-d16d-11e4-9a6a-6d53f5d45351.png)

9. Choose an image and then click the "Set as featured" button.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789287/380fc500-d16d-11e4-803f-6c8528508e4d.png)

10. Click the "Edit Featured Media" button again.
  ![image](https://cloud.githubusercontent.com/assets/486230/6789231/e69c6048-d16c-11e4-8638-9de9510d0dbb.png)

11. At this point the bug triggers. The _Edit Gallery_ window will appear again if I simply wait and don't interact at all (no mouse movement necessary).
  ![image](https://cloud.githubusercontent.com/assets/486230/6789347/9670cbc6-d16d-11e4-8fe8-9ea79e1c3f4e.png)

Looking at the DOM, it appears that when _Edit Gallery_ shows again, what's happening is that the original "Featured Image" modal is still being shown but *two additional* modals appear each set to the _Edit Gallery_ view. After closing both of these additional modals, the "Featured Image" modal will be visible.

This is how the DOM looks when the two additional modals appear. The visible modal, _Edit Gallery_, is the highlighted DIV element:
![image](https://cloud.githubusercontent.com/assets/486230/6789426/2de1bf42-d16e-11e4-91ba-d7c6fd7de070.png)

After closing the two visible modals, I'm back to "Featured Image":
![image](https://cloud.githubusercontent.com/assets/486230/6789443/559659a8-d16e-11e4-805b-a280d2f31bfc.png)

**Closed** 2015-03-24 22:06 UTC
Labels: priority: high, type: bug
