### ISSUE TITLE
on update to 0.5.2, several menu areas no longer available

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#852] opened 2015-08-18 23:55 UTC
Observed on MWEN, there is now no way to edit the footer navigation or don't miss menus,

**Comment by rnagle** [comment] 2015-08-19 01:08
So, here's what I've found so far:

- The theme locations for "Don't Miss", "Footer Navigation" and "Footer Bottom" still appear in the Appearance > Menus area of the dashboard.
- Creating and assigning menus to any of those locations works fine.
- MWEN does not include the "Don't Miss" location in its theme, so that will never actually display.
- If "Don't Miss" and "Footer Navigation" menus were ever created, I'm not sure when they would have disappeared, as nothing I've seen so far indicates the `0.5.2` caused them to go away.
- Other sites are not exhibiting this issue.

If you're *pretty sure* this was caused by the `0.5.2` update, then I'll try to dig a little deeper (I may have a vagrant snapshot I can restore to see what things looked like a few weeks ago).

**Comment by benlk** [comment] 2015-10-28 22:30
... did we have a fix for this?

**Comment by aschweigert** [comment] 2015-10-28 22:32
i don't think we ever figured it out, afaik

**Comment by benlk** [comment] 2016-04-04 19:26
Is this still a problem?

**Comment by aschweigert** [comment] 2016-04-04 19:28
haven't seen it anywhere else, probably ok to close for now

**Closed** 2016-04-04 19:32 UTC
Labels: priority: critical, type: bug
