### ISSUE TITLE
largo_trim_sentences() needs support for AP-style month abbreviations and single-letter abbreviations

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1179] opened 2016-03-22 21:44 UTC
The function: https://github.com/INN/Largo/blob/0db770f238dd3bc094b57ed2aa78e3bad5a283f4/inc/post-tags.php#L520

The following things count as the end of a sentence:

```
Mass. # State abbreviations
Jan. # Months
v. # used in court cases
Hon. # The Honorable, a title for judges
```

**Comment by aschweigert** [comment] 2016-03-22 21:46
This is a duplicate, i'll try to find the other issue momentarily...

**Comment by aschweigert** [comment] 2016-03-22 22:19
duplicate of #171

**Closed by aschweigert** 2016-03-22 22:19 UTC
Labels: priority: low, type: bug
