### ISSUE TITLE
Media Credit Hidden in Slideshow Styles

### ISSUE THREAD

**Issue by rclations** [INN/largo#1397] opened 2017-01-13 21:34 UTC
On the new slideshow styles introduced in v0.5.5, the media credit appears to be hidden by
https://github.com/INN/Largo/blob/master/lib/navis-slideshows/css/slides.css#L43

Fix is to remove the display:none and add styles for this element

**Comment by joshdarby** [comment] 2019-04-22 16:53
Closing this out since we were unable to reproduce it. 

Here is the media credit working on...

Featured media gallery:
![Screen Shot 2019-04-22 at 12 47 52 PM](https://user-images.githubusercontent.com/18353636/56512477-7d1bfb00-64fd-11e9-85e1-745d7b01acc1.png)

Inside content media gallery:
![Screen Shot 2019-04-22 at 12 48 16 PM](https://user-images.githubusercontent.com/18353636/56512491-860ccc80-64fd-11e9-81f3-87022dcf54ae.png)

Full-width expanded image from media gallery:
![Screen Shot 2019-04-22 at 12 48 26 PM](https://user-images.githubusercontent.com/18353636/56512516-96bd4280-64fd-11e9-8e6c-035adf13deb1.png)

**Closed** 2019-04-22 16:54 UTC
Labels: could not reproduce, priority: high, type: bug
