### ISSUE TITLE
Not All Post Prominence Terms Appear in Metabox on Add/Edit Post Screen

### ISSUE THREAD

**Issue by 0aveRyan** [INN/Largo#956] opened 2015-11-04 20:56 UTC
Discovered during C-HIT migration from 0.3 to 0.5.2:
C-HIT's custom prominence term disappeared from the metabox ([add metabox function here](https://github.com/INN/Largo/blob/f4ddf0b27b5fc34fb826e7ac22a9c393b4cbed1a/inc/post-metaboxes.php#L109-L128))

Checked against a few other member sites including NPQ, Oklahoma Watch and adding terms in vagrant to a site not using any Custom Terms. NPQ's custom term showed, however Oklahoma Watch's and ones added in vagrant did not. (None of the terms are added programmatically for those themes)

These terms all contained posts and were accessible via the Quick Edit bulk edit screen, but wouldn't show up in the single post edit view.

**Comment by dryanmedia** [comment] 2015-11-09 23:04
Another situation where prominence terms aren't being completely registered properly... Cornell Daily Sun. Added a handful of prominence terms to handle their homepage and while not all terms are displaying on the Add / Edit page it's the slugs shown in the Post Prominence list that have me concerned, as something is interfering with their registration.

<img width="780" alt="screen shot 2015-11-09 at 4 03 57 pm" src="https://cloud.githubusercontent.com/assets/9565066/11049452/91e7532e-86fb-11e5-946e-080bb31902d1.png">
<img width="710" alt="screen shot 2015-11-09 at 4 03 45 pm" src="https://cloud.githubusercontent.com/assets/9565066/11049451/91e63db8-86fb-11e5-8dba-72408ca43d67.png">
<img width="226" alt="screen shot 2015-11-09 at 4 03 39 pm" src="https://cloud.githubusercontent.com/assets/9565066/11049450/91e44af8-86fb-11e5-845f-ef1ddaa8e0a3.png">

**Comment by benlk** [comment] 2015-11-10 15:04
Is there another place where the options need to be added maybe?

**Comment by aschweigert** [comment] 2016-04-12 15:30
Do we know if this is still an issue?

**Comment by benlk** [comment] 2016-04-12 15:36
I do not know.

**Comment by rclations** [comment] 2016-07-18 02:57
> These terms all contained posts and were accessible via the Quick Edit bulk edit screen, but wouldn't show up in the single post edit view.

The above pull request should solve this issue.

> it's the slugs shown in the Post Prominence list that have me concerned, as something is interfering with their registration.

This part probably needs further investigation & testing to determine the cause and if it's still an issue.

**Comment by aschweigert** [comment] 2016-07-19 20:26
as far as i can tell this is resolved with that latest PR, we'll keep an eye on it but closing for now. thanks @rclations!

**Closed by aschweigert** 2016-07-19 20:26 UTC
Labels: priority: critical, type: bug
